### User Login

Not Yet Implemented

### User Register

Not Yet Implemented

### User Photo (GET)

Not Yet Implemented

### User photo (POST)

Not Yet Implemented

### User Photo (PUT)

Not Yet Implemented

### User Photo (DELETE)

Not Yet Implemented